//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRiego.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://172.17.217.145/soap/sustentabilidadWS", ConfigurationName="WeatherService.sustentabilidadWSPortType")]
    public interface sustentabilidadWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://localhost/sustentabilidadWS/service.php) del mensaje getRainPobabilityRequest no coincide con el valor predeterminado (http://172.17.217.145/soap/sustentabilidadWS)
        [System.ServiceModel.OperationContractAttribute(Action="http://172.17.217.145/sustentabilidadWS/service.php/getRainPobability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        AppRiego.WeatherService.getRainPobabilityResponse getRainPobability(AppRiego.WeatherService.getRainPobabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.17.217.145/sustentabilidadWS/service.php/getRainPobability", ReplyAction="*")]
        System.Threading.Tasks.Task<AppRiego.WeatherService.getRainPobabilityResponse> getRainPobabilityAsync(AppRiego.WeatherService.getRainPobabilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRainPobability", WrapperNamespace="http://localhost/sustentabilidadWS/service.php", IsWrapped=true)]
    public partial class getRainPobabilityRequest {
        
        public getRainPobabilityRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRainPobabilityResponse", WrapperNamespace="http://localhost/sustentabilidadWS/service.php", IsWrapped=true)]
    public partial class getRainPobabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getRainPobabilityResponse() {
        }
        
        public getRainPobabilityResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sustentabilidadWSPortTypeChannel : AppRiego.WeatherService.sustentabilidadWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sustentabilidadWSPortTypeClient : System.ServiceModel.ClientBase<AppRiego.WeatherService.sustentabilidadWSPortType>, AppRiego.WeatherService.sustentabilidadWSPortType {
        
        public sustentabilidadWSPortTypeClient() {
        }
        
        public sustentabilidadWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sustentabilidadWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sustentabilidadWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sustentabilidadWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppRiego.WeatherService.getRainPobabilityResponse AppRiego.WeatherService.sustentabilidadWSPortType.getRainPobability(AppRiego.WeatherService.getRainPobabilityRequest request) {
            return base.Channel.getRainPobability(request);
        }
        
        public string getRainPobability() {
            AppRiego.WeatherService.getRainPobabilityRequest inValue = new AppRiego.WeatherService.getRainPobabilityRequest();
            AppRiego.WeatherService.getRainPobabilityResponse retVal = ((AppRiego.WeatherService.sustentabilidadWSPortType)(this)).getRainPobability(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppRiego.WeatherService.getRainPobabilityResponse> AppRiego.WeatherService.sustentabilidadWSPortType.getRainPobabilityAsync(AppRiego.WeatherService.getRainPobabilityRequest request) {
            return base.Channel.getRainPobabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppRiego.WeatherService.getRainPobabilityResponse> getRainPobabilityAsync() {
            AppRiego.WeatherService.getRainPobabilityRequest inValue = new AppRiego.WeatherService.getRainPobabilityRequest();
            return ((AppRiego.WeatherService.sustentabilidadWSPortType)(this)).getRainPobabilityAsync(inValue);
        }
    }
}
